### ISSUE TITLE
Pi Camera V3 not taking pictues (but Live preview in homepage works)

### ISSUE THREAD

**Issue by niccolov** [photobooth-app/photobooth-app#211]
I've finally installed all the system and tested it.
Very great job! Congratulation!

I've a little problem with my new Pi Camera Module V3.

**System:**
 - OS: Raspberry Pi bullseye 64bit
 - Hardware: Raspberry Pi 3 B+
 - Camera: Pi Camera V3
- I've made a clean full installation and followed the instruction

Using Photobooth-app I see the live preview on the home page but if I try to take a picture the camera stops working.
Here the copy of the error:

2024-04-05 19:10:00,664 [ WARNING] WLED module not connected, ignoring request (wledservice.py:148)
2024-04-05 19:10:00,668 [   DEBUG] change to capture mode requested (picamera2.py:240)
2024-04-05 19:10:00,671 [    INFO] start countdown, duration_user=duration=2.0, offset_camera=0.25 (processingservice.py:161)
2024-04-05 19:10:00,731 [    INFO] switch_mode invoked, stopping stream encoder, switch mode and restart encoder (picamera2.py:265)
2024-04-05 19:10:00,842 [    INFO] Camera stopped (picamera2.py:1075)
2024-04-05 19:10:01,319 [    INFO] Configuration successful! (picamera2.py:945)
2024-04-05 19:10:01,629 [   ERROR] Uncaught exception in thread <StoppableThread(_worker_thread, started daemon 547520074176)>: <class 'RuntimeError'> Failed to allocate buffers: Impossibile allocare memoria (loggingservice.py:190)
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/home/fotobutte/.local/lib/python3.9/site-packages/photobooth/services/backends/picamera2.py", line 311, in _worker_fun
    self._switch_mode()
  File "/home/fotobutte/.local/lib/python3.9/site-packages/photobooth/services/backends/picamera2.py", line 273, in _switch_mode
    self._picamera2.switch_mode(self._current_config)
  File "/usr/lib/python3/dist-packages/picamera2/picamera2.py", line 1241, in switch_mode
    return self.dispatch_functions(functions, wait, signal_function, immediate=True)
  File "/usr/lib/python3/dist-packages/picamera2/picamera2.py", line 1203, in dispatch_functions
    return job.get_result() if wait else job
  File "/usr/lib/python3/dist-packages/picamera2/job.py", line 77, in get_result
    return self._future.result()
  File "/usr/lib/python3.9/concurrent/futures/_base.py", line 440, in result
    return self.__get_result()
  File "/usr/lib/python3.9/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/usr/lib/python3/dist-packages/picamera2/job.py", line 47, in execute
    done, result = self._functions[0]()
  File "/usr/lib/python3/dist-packages/picamera2/picamera2.py", line 1234, in switch_mode_
    self.configure_(camera_config)
  File "/usr/lib/python3/dist-packages/picamera2/picamera2.py", line 983, in configure_
    if self.allocator.allocate(stream) < 0:
RuntimeError: Failed to allocate buffers: Impossibile allocare memoria
2024-04-05 19:10:02,950 [    INFO] on_exit_state self.current_state.id='counting'  (processingservice.py:112)
2024-04-05 19:10:02,959 [    INFO] on_enter_state self.current_state.id='capture'  (processingservice.py:104)
2024-04-05 19:10:02,971 [    INFO] current capture (1/1, remaining 0) (processingservice.py:177)
2024-04-05 19:10:03,004 [   DEBUG] capture to filepath_neworiginalfile=PosixPath('media/original/image_show_20240405-191002-985841.jpg') (processingservice.py:191)
2024-04-05 19:10:03,010 [    INFO] WledService preset_shoot triggered (wledservice.py:141)
2024-04-05 19:10:03,016 [ WARNING] WLED module not connected, ignoring request (wledservice.py:148)
2024-04-05 19:10:07,018 [   ERROR] timeout receiving frames (abstractbackend.py:253)
Traceback (most recent call last):
  File "/home/fotobutte/.local/lib/python3.9/site-packages/photobooth/services/backends/abstractbackend.py", line 251, in wait_for_hq_image
    return self._wait_for_hq_image()
  File "/home/fotobutte/.local/lib/python3.9/site-packages/photobooth/services/backends/picamera2.py", line 205, in _wait_for_hq_image
    raise TimeoutError("timeout receiving frames")
TimeoutError: timeout receiving frames
2024-04-05 19:10:07,028 [   ERROR] error capture image. attempt=1/3, retrying (abstractbackend.py:254)
2024-04-05 19:10:11,030 [   ERROR] timeout receiving frames (abstractbackend.py:253)
Traceback (most recent call last):
  File "/home/fotobutte/.local/lib/python3.9/site-packages/photobooth/services/backends/abstractbackend.py", line 251, in wait_for_hq_image
    return self._wait_for_hq_image()
  File "/home/fotobutte/.local/lib/python3.9/site-packages/photobooth/services/backends/picamera2.py", line 205, in _wait_for_hq_image
    raise TimeoutError("timeout receiving frames")
TimeoutError: timeout receiving frames
2024-04-05 19:10:11,034 [   ERROR] error capture image. attempt=2/3, retrying (abstractbackend.py:254)
2024-04-05 19:10:15,037 [   ERROR] timeout receiving frames (abstractbackend.py:253)
Traceback (most recent call last):
  File "/home/fotobutte/.local/lib/python3.9/site-packages/photobooth/services/backends/abstractbackend.py", line 251, in wait_for_hq_image
    return self._wait_for_hq_image()
  File "/home/fotobutte/.local/lib/python3.9/site-packages/photobooth/services/backends/picamera2.py", line 205, in _wait_for_hq_image
    raise TimeoutError("timeout receiving frames")
TimeoutError: timeout receiving frames
2024-04-05 19:10:15,039 [   ERROR] error capture image. attempt=3/3, retrying (abstractbackend.py:254)
2024-04-05 19:10:15,040 [    INFO] set flag to indicate fault in device despite backend shall be in running mode (abstractbackend.py:239)
2024-04-05 19:10:15,042 [CRITICAL] finally failed after 3 attempts to capture image! (abstractbackend.py:260)
2024-04-05 19:10:15,043 [   ERROR] finally failed after 3 attempts to capture image! (processingservice.py:207)
Traceback (most recent call last):
  File "/home/fotobutte/.local/lib/python3.9/site-packages/photobooth/services/processingservice.py", line 195, in on_enter_capture
    image_bytes = self._aquisition_service.wait_for_hq_image()  # this function repeats to get images if one capture fails.
  File "/home/fotobutte/.local/lib/python3.9/site-packages/photobooth/services/aquisitionservice.py", line 128, in wait_for_hq_image
    image_bytes = self._main_backend.wait_for_hq_image(appconfig.backends.retry_capture)
  File "/home/fotobutte/.local/lib/python3.9/site-packages/photobooth/services/backends/abstractbackend.py", line 261, in wait_for_hq_image
    raise RuntimeError(f"finally failed after {retries} attempts to capture image!")
RuntimeError: finally failed after 3 attempts to capture image!
2024-04-05 19:10:15,057 [   ERROR] error capture image. finally failed after 3 attempts to capture image! (processingservice.py:208)
2024-04-05 19:10:15,058 [   ERROR] finally failed after 3 attempts to capture image! (processingservice.py:348)
2024-04-05 19:10:15,060 [    INFO] on_exit_state self.current_state.id='capture'  (processingservice.py:112)
2024-04-05 19:10:15,062 [CRITICAL] on_exit_capture no valid image taken! abort processing (processingservice.py:222)
2024-04-05 19:10:15,064 [    INFO] job reset, rollback captures during job (processingservice.py:331)
2024-04-05 19:10:15,066 [    INFO] on_enter_state self.current_state.id='idle'  (processingservice.py:104)
2024-04-05 19:10:15,068 [    INFO] state idle entered. (processingservice.py:127)
2024-04-05 19:10:15,069 [   DEBUG] change to preview mode requested (picamera2.py:245)
2024-04-05 19:10:15,071 [    INFO] job reset, rollback captures during job (processingservice.py:331)
2024-04-05 19:10:15,073 [   ERROR] error processing the job :| finally failed after 3 attempts to capture image! (processing.py:28)
Traceback (most recent call last):
  File "/home/fotobutte/.local/lib/python3.9/site-packages/photobooth/services/processingservice.py", line 346, in start_job_1pic
    self.start(JobModel.Typ.image, 1)
  File "/home/fotobutte/.local/lib/python3.9/site-packages/statemachine/event.py", line 54, in trigger_event
    return event_instance.trigger(self, *args, **kwargs)
  File "/home/fotobutte/.local/lib/python3.9/site-packages/statemachine/event.py", line 29, in trigger
    return machine._process(trigger_wrapper)
  File "/home/fotobutte/.local/lib/python3.9/site-packages/statemachine/statemachine.py", line 288, in _process
    return self._processing_loop()
  File "/home/fotobutte/.local/lib/python3.9/site-packages/statemachine/statemachine.py", line 303, in _processing_loop
    result = trigger()
  File "/home/fotobutte/.local/lib/python3.9/site-packages/statemachine/event.py", line 27, in trigger_wrapper
    return self._trigger(trigger_data)
  File "/home/fotobutte/.local/lib/python3.9/site-packages/statemachine/event.py", line 39, in _trigger
    if transition.execute(event_data):
  File "/home/fotobutte/.local/lib/python3.9/site-packages/statemachine/transition.py", line 140, in execute
    result = machine._activate(event_data)
  File "/home/fotobutte/.local/lib/python3.9/site-packages/statemachine/statemachine.py", line 336, in _activate
    self._callbacks_registry[target.enter].call(
  File "/home/fotobutte/.local/lib/python3.9/site-packages/statemachine/callbacks.py", line 228, in call
    return [
  File "/home/fotobutte/.local/lib/python3.9/site-packages/statemachine/callbacks.py", line 229, in <listcomp>
    callback(*args, **kwargs)
  File "/home/fotobutte/.local/lib/python3.9/site-packages/statemachine/callbacks.py", line 29, in __call__
    result = self._callback(*args, **kwargs)
  File "/home/fotobutte/.local/lib/python3.9/site-packages/statemachine/dispatcher.py", line 48, in __call__
    return self._cache(*args, **kwds)
  File "/home/fotobutte/.local/lib/python3.9/site-packages/statemachine/signature.py", line 56, in method_wrapper
    return method(*ba.args, **ba.kwargs)
  File "/home/fotobutte/.local/lib/python3.9/site-packages/photobooth/services/processingservice.py", line 212, in on_enter_capture
    raise exc
  File "/home/fotobutte/.local/lib/python3.9/site-packages/photobooth/services/processingservice.py", line 195, in on_enter_capture
    image_bytes = self._aquisition_service.wait_for_hq_image()  # this function repeats to get images if one capture fails.
  File "/home/fotobutte/.local/lib/python3.9/site-packages/photobooth/services/aquisitionservice.py", line 128, in wait_for_hq_image
    image_bytes = self._main_backend.wait_for_hq_image(appconfig.backends.retry_capture)
  File "/home/fotobutte/.local/lib/python3.9/site-packages/photobooth/services/backends/abstractbackend.py", line 261, in wait_for_hq_image
    raise RuntimeError(f"finally failed after {retries} attempts to capture image!")
RuntimeError: finally failed after 3 attempts to capture image!

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/fotobutte/.local/lib/python3.9/site-packages/photobooth/routers/processing.py", line 17, in _capture
    job()
  File "/home/fotobutte/.local/lib/python3.9/site-packages/photobooth/services/processingservice.py", line 350, in start_job_1pic
    raise RuntimeError(f"error processing the job :| {exc}") from exc
RuntimeError: error processing the job :| finally failed after 3 attempts to capture image!
2024-04-05 19:10:15,101 [CRITICAL] error processing the job :| finally failed after 3 attempts to capture image! (processing.py:29)
2024-04-05 19:10:15,103 [   ERROR] HTTPException: HTTPException(status_code=500, detail='something went wrong, Exception: error processing the job :| finally failed after 3 attempts to capture image!') (application.py:83)
2024-04-05 19:10:15,105 [    INFO] 127.0.0.1:58506 - "GET /processing/chose/1pic HTTP/1.1" 500 (h11_impl.py:477)
2024-04-05 19:10:15,263 [ WARNING] livepreview not enabled (aquisition.py:27)
2024-04-05 19:10:15,263 [    INFO] implementation signaled a fault during run! set status to fault and try to recover. (abstractbackend.py:122)
2024-04-05 19:10:15,269 [    INFO] setting device status from running to fault (abstractbackend.py:106)
2024-04-05 19:10:15,270 [   ERROR] HTTPException: HTTPException(status_code=405, detail='preview not enabled') (application.py:83)
2024-04-05 19:10:15,272 [   DEBUG] stop encoder (picamera2.py:181)
2024-04-05 19:10:15,275 [    INFO] 127.0.0.1:58506 - "GET /aquisition/stream.mjpg HTTP/1.1" 405 (h11_impl.py:477)
2024-04-05 19:10:15,661 [    INFO] Camera closed successfully. (picamera2.py:583)
2024-04-05 19:10:15,673 [   DEBUG] closed (picamera2.py:185)
2024-04-05 19:10:15,676 [   DEBUG] photobooth.services.backends.picamera2 stopped,  self._worker_thread.is_alive()=False (picamera2.py:187)
2024-04-05 19:10:15,680 [    INFO] connect_thread device status=EnumDeviceStatus.fault, so trying to start (abstractbackend.py:135)
2024-04-05 19:10:15,683 [    INFO] setting device status from fault to starting (abstractbackend.py:106)
2024-04-05 19:10:15,686 [    INFO] trying to start backend (abstractbackend.py:140)
2024-04-05 19:10:15,688 [    INFO] device is available (abstractbackend.py:144)
2024-04-05 19:10:15,696 [    INFO] Initialization successful. (picamera2.py:428)
2024-04-05 19:10:15,699 [    INFO] Camera now open. (picamera2.py:449)
2024-04-05 19:10:15,710 [   DEBUG] change to preview mode requested (picamera2.py:245)
2024-04-05 19:10:15,720 [    INFO] Configuration successful! (picamera2.py:945)
2024-04-05 19:10:15,949 [    INFO] camera_config: {'use_case': 'video', 'transform': <libcamera.Transform 'identity'>, 'colour_space': <libcamera.ColorSpace 'Rec709'>, 'buffer_count': 3, 'queue': True, 'main': {'format': 'XBGR8888', 'size': (2304, 1296), 'stride': 9216, 'framesize': 11943936}, 'lores': {'format': 'YUV420', 'size': (1280, 720), 'stride': 1280, 'framesize': 1382400}, 'raw': {'format': 'SBGGR10_CSI2P', 'size': (2304, 1296), 'stride': 2880, 'framesize': 3732480}, 'controls': {'NoiseReductionMode': <NoiseReductionModeEnum.Fast: 1>, 'FrameDurationLimits': (33333, 33333)}, 'display': 'lores', 'encode': 'lores'} (picamera2.py:147)
2024-04-05 19:10:15,954 [    INFO] camera_controls: {'ColourGains': (0.0, 32.0, None), 'AfMetering': (0, 1, 0), 'AnalogueGain': (1.1228070259094238, 16.0, None), 'Saturation': (0.0, 32.0, 1.0), 'Contrast': (0.0, 32.0, 1.0), 'AeMeteringMode': (0, 3, 0), 'AfMode': (0, 2, 0), 'AeConstraintMode': (0, 3, 0), 'AeEnable': (False, True, None), 'ExposureTime': (13, 112072753, None), 'AfPause': (0, 2, 0), 'AfRange': (0, 2, 0), 'NoiseReductionMode': (0, 4, 0), 'ScalerCrop': ((0, 0, 128, 128), (0, 0, 4608, 2592), (0, 0, 4608, 2592)), 'Sharpness': (0.0, 16.0, 1.0), 'AwbEnable': (False, True, None), 'FrameDurationLimits': (17849, 112075593, None), 'ExposureValue': (-8.0, 8.0, 0.0), 'AwbMode': (0, 7, 0), 'AeExposureMode': (0, 3, 0), 'AfSpeed': (0, 1, 0), 'AfTrigger': (0, 1, 0), 'AfWindows': ((0, 0, 0, 0), (65535, 65535, 65535, 65535), (0, 0, 0, 0)), 'Brightness': (-1.0, 1.0, 0.0), 'LensPosition': (0.0, 32.0, 1.0)} (picamera2.py:148)
2024-04-05 19:10:15,961 [    INFO] controls: <Controls: {'NoiseReductionMode': <NoiseReductionModeEnum.Fast: 1>, 'FrameDurationLimits': (33333, 33333)}> (picamera2.py:149)
2024-04-05 19:10:15,967 [    INFO] set_ae_exposure, try to set to 1 (picamera2.py:255)
2024-04-05 19:10:15,973 [    INFO] current picamera2.controls.get_libcamera_controls():{libcamera.ControlId(39, NoiseReductionMode, ControlType.Integer32): <NoiseReductionModeEnum.Fast: 1>, libcamera.ControlId(25, FrameDurationLimits, ControlType.Integer64): (33333, 33333), libcamera.ControlId(5, AeExposureMode, ControlType.Integer32): 1} (picamera2.py:262)
2024-04-05 19:10:15,978 [    INFO] stream quality Quality[appconfig.backends.picamera2_stream_quality.name]=<Quality.MEDIUM: 2> (picamera2.py:152)
2024-04-05 19:10:16,200 [    INFO] Camera started (picamera2.py:1026)
2024-04-05 19:10:16,377 [   DEBUG] autofocus set (picamera2.py:295)
2024-04-05 19:10:16,380 [   DEBUG] photobooth.services.backends.picamera2 started (picamera2.py:168)
2024-04-05 19:10:16,382 [    INFO] setting device status from starting to running (abstractbackend.py:106)
2024-04-05 19:10:16,393 [    INFO] device started, set status running (abstractbackend.py:155)
2024-04-05 19:10:26,651 [ WARNING] livepreview not enabled (aquisition.py:27)
2024-04-05 19:10:26,746 [   ERROR] HTTPException: HTTPException(status_code=405, detail='preview not enabled') (application.py:83)
2024-04-05 19:10:26,795 [    INFO] 127.0.0.1:60876 - "GET /aquisition/stream.mjpg HTTP/1.1" 405 (h11_impl.py:477)

I've noticed that when photobooth-app is live the following command doesn't work:

$ libcamera-hello list-cameras
Made X/EGL preview window
[0:08:59.413572012] [2317]  INFO Camera camera_manager.cpp:297 libcamera v0.0.5+83-bde9b04f
[0:08:59.524614384] [2333] ERROR V4L2 v4l2_device.cpp:353 'imx708': Unable to set controls: Device or resource busy
[0:08:59.831510279] [2333]  INFO RPI vc4.cpp:437 Registered camera /base/soc/i2c0mux/i2c@1/imx708@1a to Unicam device /dev/media2 and ISP device /dev/media0
[0:08:59.831734656] [2333]  INFO RPI pipeline_base.cpp:1101 Using configuration file '/usr/share/libcamera/pipeline/rpi/vc4/rpi_apps.yaml'
[0:08:59.834838166] [2317]  INFO Camera camera.cpp:840 Pipeline handler in use by another process
ERROR: *** failed to acquire camera /base/soc/i2c0mux/i2c@1/imx708@1a ***

Same error If I tri something like:
libcamera-jpeg -o prova3.jpg

If I stop the photobooth-app libcamera works again.

$ libcamera-jpeg -o prova3.jpg
Made X/EGL preview window
[0:34:58.331291190] [2775]  INFO Camera camera_manager.cpp:297 libcamera v0.0.5+83-bde9b04f
[0:34:58.559265288] [2776]  INFO RPI vc4.cpp:437 Registered camera /base/soc/i2c0mux/i2c@1/imx708@1a to Unicam device /dev/media2 and ISP device /dev/media0
[0:34:58.559456428] [2776]  INFO RPI pipeline_base.cpp:1101 Using configuration file '/usr/share/libcamera/pipeline/rpi/vc4/rpi_apps.yaml'
[0:34:58.564874022] [2775]  INFO Camera camera.cpp:1033 configuring streams: (0) 2048x1152-YUV420
[0:34:58.566279344] [2776]  INFO RPI vc4.cpp:565 Sensor: /base/soc/i2c0mux/i2c@1/imx708@1a - Selected sensor format: 2304x1296-SBGGR10_1X10 - Selected unicam format: 2304x1296-pBAA
[0:35:08.835362019] [2775]  INFO Camera camera.cpp:1033 configuring streams: (0) 4608x2592-YUV420 (1) 4608x2592-SBGGR10_CSI2P
[0:35:08.841003099] [2776]  INFO RPI vc4.cpp:565 Sensor: /base/soc/i2c0mux/i2c@1/imx708@1a - Selected sensor format: 4608x2592-SBGGR10_1X10 - Selected unicam format: 4608x2592-pBAA
Still capture image received

Can you help me to complete the process.... making the pictures?

Thanks,

Niccolò

**Comment by mgineer85** [comment]
Hey,
for what reason you chose the old raspberry system?
The error is from picamera2/libcamera which is actually only limited updated on the old system.
Please upgrade to bookworm.
Ensure you updated the system also to the latest packages with apt.

**Comment by mgineer85** [comment]
It cannot be changed in the photobooth, but I changed to catch the error and automatically restart the app instead to crash.
But this just covers the error only and does not fix it 
https://github.com/photobooth-app/photobooth-app/commit/6ae2cbe43d06ce7940aaac60da0887df1b2d1d59

**Comment by niccolov** [comment]
You're right! I've made a fresh installation with Bookworm, this time on a Raspberry 4, and the Pi Camera 3 works great! 
Thanks!

**Comment by mgineer85** [comment]
Great, thank you for providing the feedback.
So I close this issue for now.
